# Site settings
title: Shiny Flights
email: shinyflightsllc@gmail.com
url: https://www.shinyflights.com
description: 
keywords:
skills: We make aircrafts shine! 
meta_author:

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Shiny Flights LLC. All Rights Reserved.
  location: Location
  social: Social Media

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/shinyflights
  - title: facebook
    url: https://www.facebook.com/profile.php?id=61552983232959
  - title: instagram
    url: https://www.instagram.com/shinyflights/
  - title: youtube
    url: https://www.youtube.com/@pilotperson
  - title: tiktok
    url: https://www.tiktok.com/@shinyflightsllc

# Postal address (add as many lines as necessary)
address:
  - line: Austin, TX

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
